apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-meshcentral
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-meshcentral
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-meshcentral
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-meshcentral
    spec:
      containers:
      - name: meshcentral
        image: "{{ .Values.meshcentral.image.repository }}:{{ .Values.meshcentral.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 443
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: meshcentral-data
          subPath: meshcentral-data
          mountPath: /opt/meshcentral/meshcentral-data
        - name: meshcentral-data
          subPath: meshcentral-user-files
          mountPath: /opt/meshcentral/meshcentral-files
        - name: meshcentral-data
          subPath: meshcentral-backup
          mountPath: /opt/meshcentral/meshcentral-backups
        - name: meshcentral-data
          subPath: meshcentral-web
          mountPath: /opt/meshcentral/meshcentral-web
        {{- end }}
        - name: meshcentral-config
          mountPath: /opt/meshcentral/meshcentral-data/config.json
          subPath: config.json
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: meshcentral-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-meshcentral-data-pvc
      {{- end }}
      - name: config
        configMap:
          name: {{ .Release.Name }}-meshcentral-config