apiVersion: v1
kind: Service
metadata:
  name: {{ include "meshcentral.fullname" . }}
  labels:
    app.kubernetes.io/name: meshcentral
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: meshcentral
    app.kubernetes.io/instance: {{ .Release.Name }}
