meshcentral:
  image:
    repository: ghcr.io/ylianst/meshcentral
    tag: ""
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 443

  config:
    preconfiguredJson: {}

    settings:
      plugins: {}
      cert: ""
      WANonly: true
      port: 443
      redirPort: 80
      agentPong: 300
      tlsOffload: true
      selfUpdate: false
      allowFraming: true
      trustedProxy: ""
      webRTC: false
    domains:
      "":
        allowedOrigin:
          - ""
        minify: true
        newAccounts: true
        localSessionRecording: false
        userNameIsEmail: true
        certUrl: ""
  database:
    mongoDb: null
    mongoDbName: null
    mongoDbChangeStream: false
    mongoDbBulkOperations: false

    mariaDB:
      enabled: false
      secret: "mariadb-credentials" # Name of the secret
      secretKeys:
        host: "host" # Key name for the host in the secret
        user: "user" # Key name for the user in the secret
        password: "password" # Key name for the password in the secret
        database: "database" # Key name for the database name in the secret
      host: ""
      user: ""
      port: 3306
      password: ""
      connectionLimit: 10
      database: "meshcentral"
      awsrds: false
      ssl:
        caCertPath: ""
        clientCertPath: ""
        clientKeyPath: ""
        dontCheckServerIdentity: false

    sqlite3:
      enabled: false
      name: "meshcentral"
      journalMode: "delete"
      journalSize: 4096000
      autoVacuum: "incremental"
      incrementalVacuum: 100
      startupVacuum: false

    mySQL:
      enabled: false
      secret: "mysql-credentials"
      secretKeys:
        host: "host"
        user: "user"
        password: "password"
        database: "database"
      host: ""
      port: 3306
      user: ""
      password: ""
      database: "meshcentral"
      awsrds: false
      ssl:
        caCertPath: ""
        clientCertPath: ""
        clientKeyPath: ""
        dontCheckServerIdentity: false

    postgres:
      enabled: false
      secret: "postgres-credentials"
      secretKeys:
        host: "host"
        user: "user"
        password: "password"
        database: "database"
      host: ""
      user: ""
      port: 5432
      password: ""
      database: "meshcentral"

    acebase:
      enabled: false
      sponsor: false

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  host:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  pathType: Prefix

persistence:
  enabled: false
  storageClass: ""
  accessModes:
    - ReadWriteMany
  size: 10Gi
