meshcentral:
  image:
    repository: ghcr.io/ylianst/meshcentral
    tag: ""
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 443

  config:
    preconfiguredJson: {}

    settings:
      plugins: {}
      cert: ""
      WANonly: true
      port: 443
      redirPort: 80
      agentPong: 300
      tlsOffload: true
      selfUpdate: false
      allowFraming: true
      trustedProxy: ""
      webRTC: false
    domains:
      "":
        allowedOrigin:
          - ""
        minify: true
        newAccounts: true
        localSessionRecording: false
        userNameIsEmail: true
        certUrl: ""

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  host:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  pathType: Prefix

persistence:
  enabled: false
  storageClass: ""
  accessModes:
    - ReadWriteMany
  size: 10Gi
