meshcentral:
  image:
    repository: ghcr.io/ylianst/meshcentral
    tag: ""
    pullPolicy: IfNotPresent

  databaseType: none # Options: none, mariadb, mysql, postgres, sqlite3, acebase

  config:
    preconfiguredJson: {}

    settings:
      plugins: {}
      cert: ""
      WANonly: true
      port: 443
      redirPort: 80
      agentPong: 300
      tlsOffload: true
      selfUpdate: false
      allowFraming: true
      trustedProxy: ""
      webRTC: false

    domains:
      "": # Default domain configuration
        allowedOrigin:
          - ""
        minify: true
        newAccounts: true
        localSessionRecording: false
        userNameIsEmail: true
        certUrl: ""

  database:
    mariaDB:
      secret: "mariadb-credentials"
      secretKeys:
        host: "host"
        user: "user"
        password: "password"
        database: "database"
      host: ""
      user: ""
      port: 3306
      password: ""
      connectionLimit: 10
      database: "meshcentral"

    mySQL:
      secret: "mysql-credentials"
      secretKeys:
        host: "host"
        user: "user"
        password: "password"
        database: "database"
      host: ""
      port: 3306
      user: ""
      password: ""
      database: "meshcentral"

    postgres:
      secret: "postgres-credentials"
      secretKeys:
        host: "host"
        user: "user"
        password: "password"
        database: "database"
      host: ""
      port: 5432
      user: ""
      password: ""
      database: "meshcentral"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 443

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  pathType: Prefix

persistence:
  enabled: true # Enable persistence
  existingClaim: "" # (Optional) Use an existing PersistentVolumeClaim instead of creating one
  storageClass: "" # Storage Class to use for dynamic volume
  accessModes:
    - ReadWriteOnce
  size: 10Gi # Volume size
